/** Generated by scripts/optimize-launch.mjs — do not edit by hand. */

export const LAUNCH_LQIP = {
  "launch": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwBQCdASoUACQAPuVYpk0pJKOiOrM4ASAciWcAwGRE2rwWdSu5RX1+OWxm1x6j5kQRLdtuFeJ0AAD++EfjqdT8y+W7bPRNrsQrm1JRKOx39DRe/2XOGJVTggZBNcbHpMXDpBqeIFvNumtaBQjiqTfcpbnRSJ2xIOtU9kP1cfPEObMyqC2e0KTzOJTzeAAAAAA=",
  "first-run": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABQBgCdASoUACQAPulmq1CpJSOiqrgKASAdCWMAxNg6fWd1j3g1/el0pDzkTN3/Wsu4Nb9Xv2yllgC+AAD++QrQ1E0fMYvt2Y465bOmNHqX1mPMh1lU3iL0eRX0Nksx7Gu2lkJgcaTxyAhweXkus6MTVlvss6g7cjeZRqwOmnctY7tck5a5dnSO3+QPC79/9sD+Hw27y/RkvF2jo2OYx/RfDMAAAA=="
} as const;

export type LaunchImageName = keyof typeof LAUNCH_LQIP;
