#!/usr/bin/env node
/**
 * Launch imagery pipeline — build-time only.
 * 3072x5504 originals → 1080x1920 AVIF + WebP, plus a base64 LQIP so the
 * scrim never paints over an empty box on first frame.
 */
import sharp from "sharp";
import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const SRC = "scripts/assets/out";
const OUT = "public/launch";
const TARGETS = [
  { name: "launch", from: "grit-rooftop.jpg" },
  { name: "first-run", from: "grit-hands.jpg" },
];

await mkdir(OUT, { recursive: true });
const lqips = {};

for (const { name, from } of TARGETS) {
  const src = path.join(SRC, from);
  const base = sharp(src).resize(1080, 1920, { fit: "cover", position: "centre" });

  await base.clone().avif({ quality: 52, effort: 6 }).toFile(path.join(OUT, `${name}.avif`));
  await base.clone().webp({ quality: 72 }).toFile(path.join(OUT, `${name}.webp`));

  // 20px wide, blurred — inlined into the markup, never fetched.
  const tiny = await sharp(src).resize(20).blur(1.1).webp({ quality: 42 }).toBuffer();
  lqips[name] = `data:image/webp;base64,${tiny.toString("base64")}`;
}

await writeFile(
  "lib/theme/launchImagery.ts",
  `/** Generated by scripts/optimize-launch.mjs — do not edit by hand. */\n\n` +
    `export const LAUNCH_LQIP = ${JSON.stringify(lqips, null, 2)} as const;\n\n` +
    `export type LaunchImageName = keyof typeof LAUNCH_LQIP;\n`,
);
console.log("wrote", OUT, "and lib/theme/launchImagery.ts");
